Module2 task1
htmlacademy-javascript/2477377-kekstagram-2 pull request #2
Opened 2024-07-26 19:46 UTC by Ekaterina-Koromyslova

2024-08-03 19:39 UTC, ademaro commented on js/eslint.config.mjs
> +import globals from "globals";
зачем этот файл в проекте?

2024-08-03 19:45 UTC, ademaro requested changes
Было бы хорошо созвониться и обсудить более детально, наверное)

2024-08-03 19:45 UTC, ademaro commented on js/functions.js
> +let checkLength = (string = '', maxLength = 1) => {
у нас линтер подсказывает, что const вместо let, давай поправим

2024-08-03 19:45 UTC, ademaro commented on js/functions.js
> +let checkLength = (string = '', maxLength = 1) => {
Почему первый параметр по-умолчанию пустая строка? Это же обязательный параметр должен быть

2024-08-03 19:45 UTC, ademaro commented on js/functions.js
> +let checkLength = (string = '', maxLength = 1) => {
Почему максимальная длина равна 1? Немного странный выбор...

2024-08-03 19:45 UTC, ademaro commented on js/functions.js
> +    let result = string.length <= maxLength;
В качестве отступов у нас 2 пробела, а не 4

2024-08-03 19:45 UTC, ademaro commented on js/functions.js
> +      if (Number.isNaN(number)) {
зачем это условие?

2024-08-17 10:44 UTC, fyvfyv requested changes
Ко всему коду общий комментарий, что нужно поправить ошибки ESLint и настроить редактор. Всё что обсуждали на эту тему закину в телеграм

2024-08-17 10:44 UTC, fyvfyv commented on js/eslint.config.mjs
> +import globals from "globals";
Этот файл явно откуда-то скопирован / случайно оказался и его надо удалить.
Конфиг ESLint уже есть в проекте и так

2024-08-17 10:44 UTC, fyvfyv commented on js/functions.js
> +let checkLength = (string = '', maxLength = 1) => {
Повторю верхнеуровнево, что мы обсуждали по всему файлу:
1. Важно следить за `let` / `const` (но с этим и ESLint поможет)
2. Следить за разумностью значений по умолчанию

2024-08-17 10:44 UTC, fyvfyv commented on js/functions.js
> +  }
Здесь надо переписать на то, что мы обсуждали.
Важные моменты, которые ты сама рассказала:
1. Цикл запускать можно только по половине символов
2. Можно не собирать отдельную строку, а просто по ходу цикла сравнивать соответствующие символы
3. Если хотя бы один символ не совпадает — это не палиндром и можно выходить из цикла

2024-08-17 10:44 UTC, fyvfyv commented on js/functions.js
> +      }
Мы обсудили, что `parseInt` тут избыточен.

2024-08-17 10:44 UTC, fyvfyv commented on js/functions.js
> +      }
И эта проверка и `parseInt` тоже избыточны, потому что в строке result либо хранится уже валидные цифры, либо она пустая. Поэтому можно просто проверить, что если это пустая строка, то вернуть `NaN`

2024-08-18 22:40 UTC, merged